#repos:
#  - repo: local
#    hooks:
#      - id: lint-fix
#        name: Lint Fix
#        entry: make lint-fix
#        language: system
#        always_run: true
#        pass_filenames: false
#      - id: sort
#        name: Sort Imports
#        entry: make sort
#        language: system
#        always_run: true
#        pass_filenames: false
#      - id: test-cov
#        name: Test Coverage
#        entry: make test-cov
#        language: system
#        always_run: true
#        pass_filenames: false
