version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
  install:
    - requirements: source/docs/requirements.txt
    - path: .
sphinx:
  configuration: source/docs/conf.py
formats: all